# Generated by Django 3.1 on 2023-10-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20231002_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='discription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(blank=True, upload_to='photos/categories'),
        ),
    ]
